django_test/mysite/apps/blog/urls.py
from django.urls import path
from .views import index_view, article_view, catalogue_view

app_name = '[blog]'

urlpatterns = [
    path('', index_view, name='index_url'),
    path('article/<str:slug>', article_view, name='article_url'),
    path('cata/<str:slug>', catalogue_view, name='cata_url'),

]

django_test/mysite/apps/myauth/urls.py
# -*- coding: utf-8 -*-
from .views import profile_view,update_profile_view
# from .views import profile_view
from django.urls import path

app_name = '[myauth]'

urlpatterns = [
    path('profile/', profile_view,name='profile_url'),
    path('profile/update', update_profile_view,name='update_profile_url'),
]

django_test/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('accounts/', include('myauth.urls', namespace = 'myauth')),
    path('', include('blog.urls', namespace = 'blog')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # 加入这个才能显示media文件

django_test/mysite/apps/blog/models.py
from django.db import models
from django.conf import settings

# Create your models here.

# 文章分类model
class Catalogue(models.Model):
        name = models.CharField('分类名称', max_length=20)
        slug = models.SlugField('唯一标识', unique=True, default='cata_slug_default(请修改)')
        disc = models.TextField('分类介绍', max_length=300, default='请输入该分类的介绍....')

        class Meta:
                verbose_name = '文章分类'
                verbose_name_plural = verbose_name
                ordering=['name']

        def __str__(self):
                return self.name

# 文章model
class Article(models.Model):
        author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='作者')
        title = models.CharField(max_length=150, verbose_name='标题')
        summary = models.TextField('摘要', max_length=300, default='请输入文章摘要....')
        body = models.TextField(verbose_name='内容', default='请输入文章内容....')
        create_date = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)

        #slug 。这个其实就是用在文章的URL的。
        #比如你现在一篇文章的标题是“i like django”,你可以把slug设置成"i-like-django",然后显示在浏览器的地址URL就是比如这样www.example.com/article/i-like-django/
        #因为每个文章都是唯一的，这个slug也一定要唯一，所以你在里面设置的参数是unique=True。    
        slug = models.SlugField('唯一标识', unique=True, max_length=20, default='slug_input_default(请修改)')
        catalogue = models.ForeignKey(Catalogue, on_delete=models.CASCADE, verbose_name='文章分类')

        class Meta:
                verbose_name = '文章'                  #通俗易懂的名字
                verbose_name_plural = verbose_name      # 复数形式
                ordering=['-create_date']               # 降序排序

        def __str__(self):
                return self.title[:20]

django_test/mysite/apps/myauth/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill

# Create your models here.

class Myuser(AbstractUser):
    # 添加个性签名字段
    signature = models.CharField(max_length=50, blank=True, null=True, verbose_name="签名")
    avatar = ProcessedImageField(upload_to='avatar',
                             default='avatar/x01.png',
                             verbose_name='头像',
                             #图片将处理成100 x 100的尺寸
                             processors=[ResizeToFill(100,100)],)

    def __str__(self):
        return self.username

django_test/mysite/apps/myauth/forms.py
# -*- coding: utf-8 -*-
from django import forms
from .models import Myuser

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Myuser
        fields = ['avatar', 'signature'] #只显示model中指定的字段

django_test/mysite/apps/blog/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from blog.models import Article, Catalogue

# Create your views here.
def index_view(request):
    # return HttpResponse('Hello World! This is muix coding.')
    # return render(request, 'blog/index.html')
    articles = Article.objects.all()  # 获取所有文章数据
    catalogues = Catalogue.objects.all() # 获取所有分类数据

    return render(request, 
                'blog/index.html', 
                {'article_list':articles, 'cata_list':catalogues}) #返回给index用于显示
    
def article_view(request, slug):
    article = get_object_or_404(Article, slug=slug)  #获取该slug的文章
    return render(request,'blog/article_detail.html', {'article':article})   # 返回article_detail.html页面

def catalogue_view(request, slug):
    this_cata = get_object_or_404(Catalogue, slug=slug) #找到该目录
    articles = Article.objects.filter(catalogue = this_cata) # 找到属于该目录的所有文章
    catalogues = Catalogue.objects.all() # 获取所有分类数据

    return render(request, 'blog/cata_detail.html', {'article_list':articles, 'cata_list':catalogues})

django_test/mysite/apps/myauth/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from .forms import ProfileForm

# Create your views here.

#需要登陆才可以
@login_required
def update_profile_view(request):
    if request.method == 'POST':
        # request.FILES  for upload files
        form = ProfileForm(request.POST,request.FILES,instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('myauth:profile_url')
    else:
        # POST
        form = ProfileForm(instance = request.user)
    return render(request,'myauth/update_profile.html',context={'form':form})
def profile_view(request):
    return render(request,'myauth/user_profile.html')

django_test/mysite/templates/myauth/update_profile.html
{% extends "blog/base.html" %}

{% load static %}

{% block base_content %}

<style>
.col-center-block {
        float: none;
        display: block;
        margin: 0 auto;
        /* margin-left: auto; margin-right: auto; */
}
</style>

<div class="container">
    <div class="row">
         <div class="col-xs-6 col-md-4 col-center-block">
             <form class="update_profile", method="post" enctype="multipart/form-data" action="{% url 'myauth:update_profile_url' %}">
               {% csrf_token %}
               {{ form.as_p }}
               <button class="pull-right btn btn-primary" type="submit">确认更新</button>
             </form>
         </div>
    </div>
</div>
  
{% endblock  %}

django_test/mysite/templates/myauth/user_profile.html
{% extends "blog/base.html" %}

{% load static %}

{% block base_content %}

<style>
.col-center-block {
        float: none;
        display: block;
        margin: 0 auto;
        /* margin-left: auto; margin-right: auto; */
}
</style>

<div class="container">
    <div class="row">
         <div class="col-xs-6 col-md-4 col-center-block">
             <ul class="list-group">
               <li class="list-group-item text-center" style="border:0px">
                    <img class="avatar" src = "{{user.avatar.url}}" alt="{{user.username}}" style="width:100px"></img>
               </li>
               <li class="list-group-item" style="border:0px">
                    <h4><span>用户名：</span><span>{{user.username}}</span> </h4>
               </li>
               <li class="list-group-item" style="border:0px">
                    <h4><span>邮&emsp;箱：</span><span>{{user.email}}</span> </h4>
               </li>
               <li class="list-group-item" style="border:0px">
                    <h4><span>签&emsp;名：</span>{{user.signature}}</h4>
               </li>
               <a class="pull-right btn btn-primary" style="margin-right: 20px" href="{% url 'myauth:update_profile_url' %}">修改资料</a>
               <a class="pull-right btn btn-primary" style="margin-right: 20px" href="{% url 'account_change_password' %}">修改密码</a>
            </ul>
         </div>
    </div>
</div>

{% endblock %}